#!/usr/bin/env bash

prompt_artisan_command() {
  # if no argument is passed, prompt the user for one
    if [ -z "$2" ]; then
      read -rp "Enter the Artisan command you want to run (e.g., 'route:list'): " ARTISAN_COMMAND
      if [ -z "$ARTISAN_COMMAND" ]; then
        echo "=== No command entered. Returning to menu."
        show_menu
        exit 0
      fi
      run_artisan_command "$ARTISAN_COMMAND"
      exit 0
    fi
}

run_artisan_command() {
  # Execute the site-ssh command with proper user and directory context
  (cd "$COMMANDS_DIR" && ./site-ssh -h=web -c="cd /var/www/site && php artisan $1")
  # "site-ssh" -h=web -c="cd ${WEB_SERVER_ROOT} && cd ../ && sudo -H -u www-data bash"
}

run_debug_artisan_command() {
  (cd "$COMMANDS_DIR" && ./site-ssh -h=web -c="cd /var/www/site && XDEBUG_MODE=debug XDEBUG_CONFIG=\"client_port=$XDEBUG_CLI_PORT\" php artisan $1")
}
