#!/usr/bin/env bash

laravel_post_install() {
  # Run Composer install
  step_text "Installing Composer dependencies..."
  ./run-local composer install
  step_text "☑️ Composer install process done"

  # Generate Laravel APP_KEY
  if grep -q "APP_KEY=base64:[A-Za-z0-9+/]" "$APP_ENV_FILE"; then
    step_text "☑️ APP_KEY value found in .env file. Skipping key generation."
  else
    step_text "Generating Laravel APP_KEY..."
    CMD="cd /var/www/site && php artisan key:generate"
    ./run-local ssh-web "$CMD"
    step_text "☑️ Laravel APP_KEY generated."
  fi

  # Run database migrations
  step_text "🏃‍♀️ Running database migrations..."
  ./run-local artisan migrate
}
